{% set name = "pdfo" %}
{% set version = "2.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdfo-{{ version }}.tar.gz
  sha256: d5191ce22bfc7033295d6b7d229d3efd1ca6f74dc8fe3c8ff400b08943bd499f

build:
  number: 0
  skip: true  # [win and python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - pip
    - numpy >=1.20.0
    - python  # [py>=37]
  run:
    - numpy >=1.20.0
    - python  # [py>=37]

test:
  imports:
    - pdfo
  commands:
    - pip check
    - python -m pdfo.tests.test_pdfo
  requires:
    - pip

about:
  home: https://www.pdfo.net
  summary: PDFO - Powell's Derivative-Free Optimization solvers
  license: LGPL-3.0-or-later
  license_file: LICENCE.txt

extra:
  recipe-maintainers:
    - ragonneau
    - AntoineD
